version: '3.8'
services:
  backend:
    image: smartfarm-backend:0.0.1
    ports:
      - "18081:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://203.241.228.50:13307/smartfarm?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "mega123"

  influxdb:
    container_name: influxdb
    image: influxdb:2.2-alpine
    ports:
      - "8086:8086"
    hostname: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=mega
      - DOCKER_INFLUXDB_INIT_PASSWORD=mega123!@#
      - DOCKER_INFLUXDB_INIT_BUCKET=smartfarm
      - DOCKER_INFLUXDB_INIT_ORG=95f96cb422f582d3
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=oSghfVuohVj8bD8cgPx_Ros-9cnYT4XKhIMSEETCxkBQRR3HQtfNLjm9QeR9EV7sQMd0_b151HGDHdL3YTdBNQ==
    volumes:
      - ./influxdb:/var/lib/influxdb
#  mysql:
#    container_name: mysql5.7
#    image: library/mysql:5.7
#    platform: linux/amd64
#    volumes:
#      - db_datas:/var/lib/mysql
#      - ./db/mysql/init:/docker-entrypoint-initdb.d
#    hostname: mysql
#    environment:
#      MYSQL_DATABASE: smartfarm
#      MYSQL_ROOT_PASSWORD: mega123
#      MYSQL_ROOT_HOST: '%'
#      TZ: Asia/Seoul
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#    ports:
#      - "13307:3306"

volumes:
  influxdb_data:
  db_datas:
