version: '3.8'
services:
  smartfarm-backend:
    image: smartfarm-backend:0.1
    ports:
      - "18081:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://203.241.228.50:13307/smartfarm?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "mega123"
  smartfarm-frontend:
    image: jadru/smartfarm-dashboard:1.0
    ports:
      - "3001:3000"
    restart: always
    environment:
      VITE_APP_API_URL: http://203.241.228.50:18081/api
      VITE_WEATHER_API_URL: http://apis.data.go.kr/1360000
      
